name: balqees
description: "A new Flutter project with enhanced UI and functionality."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.5.4 <4.0.0'  # Using range notation for better compatibility

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Core
  cupertino_icons: ^1.0.8
  provider: ^6.1.4

  # Firebase
  firebase_core: ^2.22.0
  firebase_auth: ^4.14.0
  cloud_firestore: ^4.13.1
  firebase_database: ^10.3.5
  firebase_messaging: ^14.7.4

  # Storage
  shared_preferences: ^2.5.3

  # UI
  google_fonts: ^6.2.1
  cached_network_image: ^3.4.1
  flutter_staggered_grid_view: ^0.7.0
  lottie: ^2.6.0
  carousel_slider: ^5.0.0
  flutter_animate: ^4.5.2

  # Maps & Location
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  location: ^7.0.1
  geocoding: ^3.0.0

  # Timelines
  timelines: ^0.1.0
  timeline_tile: ^2.0.0

  # Utils
  uuid: ^4.5.1
  device_info_plus: ^11.3.0
  url_launcher: ^6.3.1
  flutter_local_notifications: ^15.1.1
  animated_text_kit: ^4.2.3
  shimmer: ^3.0.0
  connectivity_plus: ^6.1.3
  flutter_svg: ^2.1.0
  flutter_rating_bar: ^4.0.1
  googleapis_auth: ^1.6.0
  flutter_dotenv: ^5.2.1
  flutter_gen: ^5.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1  # ✅ لتغيير الأيقونة

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/main.png"  # ✅ مسار صورة الأيقونة

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/logo.svg
    - assets/images/main.png
    - assets/images/logosvg.svg
    - assets/images/pattern.svg
    - assets/images/
    - assets/animations/
    - assets/animations/optimized-lottie.json
    - assets/animations/brown.lottie
    - assets/animations/white.lottie
    - assets/animations/white.json
    - assets/animations/x2.json

  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-Regular.ttf
        - asset: assets/fonts/Tajawal-Medium.ttf
          weight: 500
        - asset: assets/fonts/Tajawal-Bold.ttf
          weight: 700
        - asset: assets/fonts/Tajawal-Black.ttf
          weight: 900


