// lib/firebase_options.dart
// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAgY1fuixPv8piudCoeBJ_yiTANVEw9Yg',
    appId: '1:967307852599:web:3621c896e89389a7e338b2',
    messagingSenderId: '967307852599',
    projectId: 'balqees-restaurant',
    authDomain: 'balqees-restaurant.firebaseapp.com',
    storageBucket: 'balqees-restaurant.firebasestorage.app',
    measurementId: 'G-TRHCBYTE0R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuc1updwUAtRRUHXTdfD9231yQzaeCFCY',
    appId: '1:967307852599:android:23ec3ddcf7b8e922e338b2',
    messagingSenderId: '967307852599',
    projectId: 'balqees-restaurant',
    storageBucket: 'balqees-restaurant.firebasestorage.app',
    databaseURL: 'https://balqees-restaurant-default-rtdb.europe-west1.firebasedatabase.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjD5_zdgtLEuxOJH8xUnYo4i7NFmwIDgA',
    appId: '1:967307852599:ios:de6ff3e2262ceabee338b2',
    messagingSenderId: '967307852599',
    projectId: 'balqees-restaurant',
    storageBucket: 'balqees-restaurant.firebasestorage.app',
    iosBundleId: 'com.example.balqees',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjD5_zdgtLEuxOJH8xUnYo4i7NFmwIDgA',
    appId: '1:967307852599:ios:de6ff3e2262ceabee338b2',
    messagingSenderId: '967307852599',
    projectId: 'balqees-restaurant',
    storageBucket: 'balqees-restaurant.firebasestorage.app',
    iosBundleId: 'com.example.balqees',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAgY1fuixPv8piudCoeBJ_yiTANVEw9Yg',
    appId: '1:967307852599:web:d8363dd0570cb2e5e338b2',
    messagingSenderId: '967307852599',
    projectId: 'balqees-restaurant',
    authDomain: 'balqees-restaurant.firebaseapp.com',
    storageBucket: 'balqees-restaurant.firebasestorage.app',
    measurementId: 'G-DJPRMCN3E1',
  );
}